web prog 3/MovieArchiveTemplate/MovieArchiveTemplate/Areas/Admin/Controllers/UsersController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MovieArchiveTemplate.Models;
using MovieArchiveTemplate.Repositories;

namespace MovieArchiveTemplate.Areas.Admin.Controllers
{
    public class UsersController : Controller
    {
        private MovieArchiveDB db = new MovieArchiveDB();

        // GET: Admin/Users
        public ActionResult Index(int? page, string sorting)
        {
            var userList = db.User.ToList();


            #region [SIRALAMA]
            // ------------------- SIRALAMA --------------------

            // Burada controller çağrılırken "?sorting=xxx_ifade" şeklinde parametre gelir.
            if (string.IsNullOrEmpty(sorting))
            {
                sorting = "LNameAsc";
            }
            ViewBag.RegisterDateSortParam = sorting == "RegisterDateAsc" ? "RegisterDateDesc" : "RegisterDateAsc";
            ViewBag.LNameSortParam = sorting == "LNameDesc" ? "LNameAsc" : "LNameDesc";

            switch (sorting)
            {
                case "RegisterDateAsc":
                    userList = userList.OrderBy(m => m.RegisterDate).ToList();
                    ViewBag.CurrentSortParam = "RegisterDateDesc";
                    ViewBag.CurrentDDLText = "Register Date";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-desc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda çoktan aza sıralar.";
                    break;
                case "RegisterDateDesc":
                    userList = userList.OrderByDescending(m => m.RegisterDate).ToList();
                    ViewBag.CurrentSortParam = "RegisterDateAsc";
                    ViewBag.CurrentDDLText = "Register Date";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-asc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda azdan çoka sıralar.";
                    break;
                case "LNameAsc":
                    userList = userList.OrderBy(m => m.LName).ToList();
                    ViewBag.CurrentSortParam = "LNameDesc";
                    ViewBag.CurrentDDLText = "Last Name";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-desc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda çoktan aza sıralar.";
                    break;
                case "LNameDesc":
                    userList = userList.OrderByDescending(m => m.LName).ToList();
                    ViewBag.CurrentSortParam = "LNameAsc";
                    ViewBag.CurrentDDLText = "Last Name";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-asc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda azdan çoka sıralar.";
                    break;
                default:
                    userList = userList.OrderBy(m => m.LName).ToList();
                    ViewBag.CurrentSortParam = "LNameDesc";
                    ViewBag.CurrentDDLText = "Last Name";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-desc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda çoktan aza sıralar.";
                    break;
            }
            // ------------------- SIRALAMA --------------------
            #endregion

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View("Index", userList.ToPagedList(pageNumber, pageSize));
        }

        // GET: Admin/Users/Details?userID=id
        public ActionResult Details(int? userID)
        {
            if (userID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.User.Find(userID);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Admin/Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(User user)
        {
            if (ModelState.IsValid)
            {
                db.User.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Admin/Users/Edit?userID=id
        public ActionResult Edit(int? userID)
        {
            if (userID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.User.Find(userID);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Admin/Users/Edit?userID=id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Admin/Users/Delete?userID=id
        public ActionResult Delete(int? userID)
        {
            if (userID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.User.Find(userID);
            if (user == null)
            {
                return HttpNotFound();
            }
            db.User.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

web prog 3/MovieArchiveTemplate/MovieArchiveTemplate/Controllers/MoviesController.cs
using MovieArchiveTemplate.Models.ViewModels;
using MovieArchiveTemplate.Repositories;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieArchiveTemplate.Controllers
{
    public class MoviesController : Controller
    {
        MovieArchiveDB db = new MovieArchiveDB();

        public ActionResult MoviesThisWeek(int? page, string sorting)
        {
            var contentMovies = db.Movie.OrderByDescending(m => m.ReleaseDate).ToList();
            NMainPageDTO obj = new NMainPageDTO();
            obj.Categories = db.Genre.OrderBy(c => c.GenreName).ToList();
            obj.FutureMovies = db.Movie.OrderByDescending(m => (m.ReleaseDate >= DateTime.Now)).Take(3).ToList();
            obj.RandomMovies = (from result in contentMovies.AsEnumerable() orderby Guid.NewGuid() select result).Take(3).ToList();

            ViewBag.MainPageDTO = obj;

            #region [SIRALAMA]
            // ------------------- SIRALAMA --------------------

            // Burada controller çağrılırken "?sorting=xxx_ifade" şeklinde parametre gelir.
            if (string.IsNullOrEmpty(sorting))
            {
                sorting = "ReleaseDateDesc";
            }
            ViewBag.ReleaseDateSortParam = sorting == "ReleaseDateAsc" ? "ReleaseDateDesc" : "ReleaseDateAsc";
            ViewBag.RaitingSortParam = sorting == "RaitingDesc" ? "RaitingAsc" : "RaitingDesc";

            // Gelen sıralama ifadesine göre sıralama yapılır.
            DateTime temp = DateTime.Now.AddDays(-7);
            switch (sorting)
            {
                case "ReleaseDateAsc":
                    contentMovies = db.Movie.Where(m => (m.ReleaseDate >= temp && m.ReleaseDate <= DateTime.Now)).OrderBy(m => m.ReleaseDate).ToList();
                    ViewBag.CurrentSortParam = "ReleaseDateDesc";
                    ViewBag.CurrentDDLText = "Release Date";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-desc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda çoktan aza sıralar.";
                    break;
                case "ReleaseDateDesc":
                    contentMovies = db.Movie.Where(m => (m.ReleaseDate >= temp && m.ReleaseDate <= DateTime.Now)).OrderByDescending(m => m.ReleaseDate).ToList();
                    ViewBag.CurrentSortParam = "ReleaseDateAsc";
                    ViewBag.CurrentDDLText = "Release Date";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-asc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda azdan çoka sıralar.";
                    break;
                case "RaitingAsc":
                    contentMovies = db.Movie.Where(m => (m.ReleaseDate >= temp && m.ReleaseDate <= DateTime.Now)).OrderBy(m => m.Raiting).ToList();
                    ViewBag.CurrentSortParam = "RaitingDesc";
                    ViewBag.CurrentDDLText = "Raiting";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-desc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda çoktan aza sıralar.";
                    break;
                case "RaitingDesc":
                    contentMovies = db.Movie.Where(m => (m.ReleaseDate >= temp && m.ReleaseDate <= DateTime.Now)).OrderByDescending(m => m.Raiting).ToList();
                    ViewBag.CurrentSortParam = "RaitingAsc";
                    ViewBag.CurrentDDLText = "Raiting";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-asc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda azdan çoka sıralar.";
                    break;
                default:
                    contentMovies = db.Movie.Where(m => (m.ReleaseDate >= temp && m.ReleaseDate <= DateTime.Now)).OrderByDescending(m => m.ReleaseDate).ToList();
                    ViewBag.CurrentSortParam = "ReleaseDateAsc";
                    ViewBag.CurrentDDLText = "Release Date";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-asc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda azdan çoka sıralar.";
                    break;
            }
            // ------------------- SIRALAMA --------------------
            #endregion


            int pageSize = 5;
            int pageNumber = (page ?? 1);

            return View("MoviesThisWeek", contentMovies.ToPagedList(pageNumber, pageSize));
        }


        public ActionResult MoviesComingSoon(int? page, string sorting)
        {
            var contentMovies = db.Movie.Where(m => m.ReleaseDate >= DateTime.Now).ToList();
            NMainPageDTO obj = new NMainPageDTO();
            obj.Categories = db.Genre.OrderBy(c => c.GenreName).ToList();
            obj.FutureMovies = db.Movie.Where(m => (m.ReleaseDate >= DateTime.Now)).Take(3).ToList();
            obj.RandomMovies = (from result in contentMovies.AsEnumerable() orderby Guid.NewGuid() select result).Take(3).ToList();

            ViewBag.MainPageDTO = obj;

            #region [SIRALAMA]
            // ------------------- SIRALAMA --------------------

            // Burada controller çağrılırken "?sorting=xxx_ifade" şeklinde parametre gelir.
            if (string.IsNullOrEmpty(sorting))
            {
                sorting = "ReleaseDateDesc";
            }
            ViewBag.ReleaseDateSortParam = sorting == "ReleaseDateAsc" ? "ReleaseDateDesc" : "ReleaseDateAsc";
            ViewBag.RaitingSortParam = sorting == "RaitingDesc" ? "RaitingAsc" : "RaitingDesc";

            // Gelen sıralama ifadesine göre sıralama yapılır.
            switch (sorting)
            {
                case "ReleaseDateAsc":
                    contentMovies = db.Movie.Where(m => (m.ReleaseDate >= DateTime.Now)).OrderBy(m => m.ReleaseDate).ToList();
                    ViewBag.CurrentSortParam = "ReleaseDateDesc";
                    ViewBag.CurrentDDLText = "Release Date";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-desc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda çoktan aza sıralar.";
                    break;
                case "ReleaseDateDesc":
                    contentMovies = db.Movie.Where(m => (m.ReleaseDate >= DateTime.Now)).OrderByDescending(m => m.ReleaseDate).ToList();
                    ViewBag.CurrentSortParam = "ReleaseDateAsc";
                    ViewBag.CurrentDDLText = "Release Date";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-asc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda azdan çoka sıralar.";
                    break;
                case "RaitingAsc":
                    contentMovies = db.Movie.Where(m => (m.ReleaseDate >= DateTime.Now)).OrderBy(m => m.Raiting).ToList();
                    ViewBag.CurrentSortParam = "RaitingDesc";
                    ViewBag.CurrentDDLText = "Raiting";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-desc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda çoktan aza sıralar.";
                    break;
                case "RaitingDesc":
                    contentMovies = db.Movie.Where(m => (m.ReleaseDate >= DateTime.Now)).OrderByDescending(m => m.Raiting).ToList();
                    ViewBag.CurrentSortParam = "RaitingAsc";
                    ViewBag.CurrentDDLText = "Raiting";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-asc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda azdan çoka sıralar.";
                    break;
                default:
                    contentMovies = db.Movie.Where(m => (m.ReleaseDate >= DateTime.Now)).OrderByDescending(m => m.ReleaseDate).ToList();
                    ViewBag.CurrentSortParam = "ReleaseDateAsc";
                    ViewBag.CurrentDDLText = "Release Date";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-asc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda azdan çoka sıralar.";
                    break;
            }
            // ------------------- SIRALAMA --------------------
            #endregion

            int pageSize = 5;
            int pageNumber = (page ?? 1);

            return View("MoviesComingSoon", contentMovies.ToPagedList(pageNumber, pageSize));
        }


        public ActionResult MovieDetails(int movieID)
        {
            var contentMovies = db.Movie.Where(m => m.ReleaseDate >= DateTime.Now).ToList();
            NMainPageDTO obj = new NMainPageDTO();
            obj.Categories = db.Genre.OrderBy(c => c.GenreName).ToList();
            obj.FutureMovies = db.Movie.Where(m => (m.ReleaseDate >= DateTime.Now)).Take(3).ToList();
            obj.RandomMovies = (from result in contentMovies.AsEnumerable() orderby Guid.NewGuid() select result).Take(3).ToList();

            ViewBag.MainPageDTO = obj;

            var movie = db.Movie.Where(m => m.MovieID == movieID).FirstOrDefault();

            return View(movie);
        }


        public ActionResult MovieList(int genreID, int? page, string sorting)
        {
            var movies = db.Movie.Where(m => m.ReleaseDate >= DateTime.Now).ToList();
            NMainPageDTO obj = new NMainPageDTO();
            obj.Categories = db.Genre.OrderBy(c => c.GenreName).ToList();
            obj.FutureMovies = db.Movie.Where(m => (m.ReleaseDate >= DateTime.Now)).Take(3).ToList();
            obj.RandomMovies = (from result in movies.AsEnumerable() orderby Guid.NewGuid() select result).Take(3).ToList();

            ViewBag.MainPageDTO = obj;

            var tempGenre = db.Genre.Where(g => g.GenreID == genreID).First();
            ViewBag.Title = tempGenre.GenreName;

            var contentMovies = tempGenre.Movie.ToList();
            #region [SIRALAMA]
            // ------------------- SIRALAMA --------------------

            // Burada controller çağrılırken "?sorting=xxx_ifade" şeklinde parametre gelir.
            if (string.IsNullOrEmpty(sorting))
            {
                sorting = "ReleaseDateDesc";
            }

web prog 3/MovieArchiveTemplate/MovieArchiveTemplate/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@using MovieArchiveTemplate.Repositories;
@using MovieArchiveTemplate.Models.ViewModels;
@{
    var userRepo = new UserRepository().GetUser(Convert.ToInt32(Session["User"]));
    if (userRepo.IsSuccessful)
    {
        if (userRepo.Data.MemberType == MemberType.User)
        {
            Response.Redirect("~/Home");
        }
    }
    else
    {
        Response.Redirect("~/Home");
    }
}


<!DOCTYPE html>

<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title</title>

    @Styles.Render("~/assets/css")


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">@MovieArchiveTemplate.Resource.lang.FilmArşivAdmin</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i>&nbsp;<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="@Url.Action("Profile", "Users")" id="@userRepo.Data.UserID"><i class="fa fa-fw fa-user"></i>&nbsp;@userRepo.Data.FName @userRepo.Data.LName</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "../Home")"><i class="fa fa-fw fa-envelope"></i>&nbsp;@MovieArchiveTemplate.Resource.lang.SiteyeGit</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="@Url.Action("Logout", "Home")"><i class="fa fa-fw fa-power-off"></i> @MovieArchiveTemplate.Resource.lang.Çıkış</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    @if (HttpContext.Current.Session["Culture"].ToString() == "tr")
                    {
                        <a href="@Url.Action("ChangeCulture", "Home", new { lang = Country.en.ToString(), returnUrl = this.Request.RawUrl })">
                            <img src="~/Content/img/flags/flagEN.png" title="English" />
                        </a>
                    }
                    else
                    {
                        <a href="@Url.Action("ChangeCulture", "Home", new { lang = Country.tr.ToString(), returnUrl = this.Request.RawUrl })">
                            <img src="~/Content/img/flags/flagTR.png" title="Türkçe" />
                        </a>
                    }
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li class="active">
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo">
                            <i class="fa fa-fw fa-edit"></i> @MovieArchiveTemplate.Resource.lang.İçerikYönetim <i class="fa fa-fw fa-caret-down"></i>
                        </a>
                        <ul id="demo" class="collapse">
                            <li>
                                @Html.ActionLink(MovieArchiveTemplate.Resource.lang.Filmİşlemleri, "Index", "Movies")
                            </li>
                            <li>
                                @Html.ActionLink(MovieArchiveTemplate.Resource.lang.FilmTürleriİşlemleri, "Index", "Genres")
                            </li>
                            <li>
                                @Html.ActionLink(MovieArchiveTemplate.Resource.lang.Aktörİşlemleri, "Index", "Actors")
                            </li>
                            <li>
                                @Html.ActionLink(MovieArchiveTemplate.Resource.lang.Yönetmenİşlemleri, "Index", "Directors")
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Users")"><i class="fa fa-fw fa-wrench"></i> @MovieArchiveTemplate.Resource.lang.Kullanıcıİşlemler</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>


        <div id="page-wrapper">
            @RenderBody()
        </div><!-- /#page-wrapper -->
    </div><!-- /#wrapper -->


    @Scripts.Render("~/assets/js")
    @Scripts.Render("~/assets/js/plugins")
    @RenderSection("additionalJs", required: false)

</body>
</html>